baseURL = "https://tsuki126.github.io/"
theme = "hugo-bearblog"
title = "Tsuki126"
copyright = "Copyright © 2024, Tsuki126."
languageCode = "zh-CN"

enableRobotsTXT = true
hasCJKLanguage = true

[permalinks]
  notes = "/notes/:slug/"
  blog = "/blog/:slug/"
  categories = "/categories/:slug/"
  tags = "/tags/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "安全工程师的技术思考与实践笔记"
  favicon = "images/avatar.png"
  images = ["images/avatar.png"]
  title = "Tsuki126"
  dateFormat = "2006-01-02"
  hideMadeWithLine = true
  enablePostNavigator = true

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[", "\\]"], ["$$", "$$"]]
          inline = [["\\(", "\\)"]]
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "Tsuki126"
  email = "tsukin126@gmail.com"

[[menus.main]]
  identifier = "notes"
  name = "随笔"
  url = "/notes/"
  weight = 2

[[menus.main]]
  identifier = "blog"
  name = "博客"
  url = "/blog/"
  weight = 3

[[menus.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 4