baseURL = "https://tsuki126.github.io/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt-0.2.11"

# 网站标题
title = "Tsuki126's Blog"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]# 副标题
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true

# 作者配置
[author]
name = "Tsuki126"
email = "tsukin126@gmail.com"
link = "https://tsuki126.github.io/"

# 菜单配置
[menu]
[[menu.main]]
weight = 1
identifier = "home"
pre = ""
post = ""
name = "首页"
url = "/"
title = ""

[[menu.main]]
weight = 2
identifier = "security"
pre = ""
post = ""
name = "安全"
url = "/categories/security"
title = ""

[[menu.main]]
weight = 2
identifier = "develop"
pre = ""
post = ""
name = "开发"
url = "/categories/develop"
title = ""

[[menu.main]]
weight = 4
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""

[[menu.main]]
weight = 5
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""

[[menu.main]]
weight = 6
identifier = "about"
pre = ""
post = ""
name = "关于"
url = "/about/"
title = ""

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
